### ISSUE TITLE
Can't build on Windows

### ISSUE THREAD

**Issue by ghost** [ruabmbua/enet-sys#23]
```
PS C:\Users\Admin\Documents\dftest> cargo build
   Compiling enet-sys v1.0.4
error: failed to run custom build command for `enet-sys v1.0.4`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `C:\Users\Admin\Documents\dftest\target\debug\build\enet-sys-2af32fe846c91f07\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bindgen-0.65.1\ir\context.rs:1994:26:
  Non floating-type complex? Type(_Complex _Float16, kind: Complex, cconv: 100, decl: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None), canon: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None)), Type(_Float16, kind: Float16, cconv: 100, decl: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None), canon: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None))
  stack backtrace:
     0:     0x7ff654b40cda - std::sys_common::backtrace::_print::impl$0::fmt
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\sys_common\backtrace.rs:44
     1:     0x7ff654b6414b - core::fmt::rt::Argument::fmt
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\core\src\fmt\rt.rs:138
     2:     0x7ff654b6414b - core::fmt::write
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\core\src\fmt\mod.rs:1094
     3:     0x7ff654b3bc31 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\io\mod.rs:1714
     4:     0x7ff654b40a5a - std::sys_common::backtrace::_print
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\sys_common\backtrace.rs:47
     5:     0x7ff654b40a5a - std::sys_common::backtrace::print
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\sys_common\backtrace.rs:34
     6:     0x7ff654b4367a - std::panicking::default_hook::closure$1
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\panicking.rs:270
     7:     0x7ff654b432e8 - std::panicking::default_hook
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\panicking.rs:290
     8:     0x7ff654b43d2e - std::panicking::rust_panic_with_hook
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\panicking.rs:707
     9:     0x7ff654b43c1d - std::panicking::begin_panic_handler::closure$0
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\panicking.rs:599
    10:     0x7ff654b41999 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\sys_common\backtrace.rs:170
    11:     0x7ff654b43920 - std::panicking::begin_panic_handler
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\panicking.rs:595
    12:     0x7ff654b6d645 - core::panicking::panic_fmt
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\core\src\panicking.rs:67
    13:     0x7ff6546df9e7 - bindgen::ir::context::BindgenContext::next_item_id::hd9de428854eeb2f1
    14:     0x7ff6546dedf5 - bindgen::ir::context::BindgenContext::builtin_or_resolved_ty::h04370afef562dd6c
    15:     0x7ff654788077 - bindgen::ir::item::Item::from_ty_or_ref_with_id::h57fefd4f047a4916
    16:     0x7ff654787df8 - bindgen::ir::item::Item::from_ty_or_ref::h175189cf9e6631d1 
    17:     0x7ff65477e1af - bindgen::ir::function::args_from_ty_and_cursor::{{closure}}::h763ef080e57d876a
    18:     0x7ff65476d9e7 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::h35eacd8910bc93cf
    19:     0x7ff65470cec6 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::hbf010e6b40ada2e5
    20:     0x7ff6547ad197 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter::h2eb634c7d9f24546
    21:     0x7ff6547c0cc1 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h5b2a018e43505ed1
    22:     0x7ff6547bfe1a - <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter::h83e2cd8e5d73aec3
    23:     0x7ff654712181 - core::iter::traits::iterator::Iterator::collect::h4c98d41d0853e3d3
    24:     0x7ff65477de4b - bindgen::ir::function::cursor_mangling::h5445470789da9a01  
    25:     0x7ff65477e795 - bindgen::ir::function::FunctionSig::from_ty::h6975a5c75727d4e0
    26:     0x7ff65470092f - bindgen::ir::ty::Type::from_clang_ty::he13c210bd5ba49b6    
    27:     0x7ff6547895ea - bindgen::ir::item::Item::from_ty::hb453bc6e2d84d51f        
    28:     0x7ff654788953 - bindgen::ir::item::Item::from_ty::hb453bc6e2d84d51f        
    29:     0x7ff654787347 - bindgen::ir::item::Item::parse::h569f79d2f5eed971
    30:     0x7ff6546b32c9 - bindgen::parse_one::h284fa1ab09c63b0c
    31:     0x7ff6546b388a - bindgen::parse::{{closure}}::{{closure}}::h78a8d3b6b51a527f
    32:     0x7ff65467861e - bindgen::clang::is_valid_identifier::{{closure}}::h38ed9e3d245d5418
    33:     0x7ffc772ebc8e - <unknown>
    34:     0x7ffc772ea1b6 - <unknown>
    35:     0x7ffc772e70f4 - <unknown>
    36:     0x7ffc772e67ec - <unknown>
    37:     0x7ffc77308abb - clang_visitChildren
    38:     0x7ff654971bed - clang_sys::clang_visitChildren::h5794846b67ac0190
    39:     0x7ff654675eb9 - bindgen::clang::Cursor::visit::hb91495c9312e74fd
    40:     0x7ff6546b3837 - bindgen::parse::{{closure}}::hc7984285e3fc1fcf
    41:     0x7ff6546e14d0 - bindgen::ir::context::BindgenContext::with_module::hd9c740a4a0ebfca6
    42:     0x7ff6546b35a1 - bindgen::parse_one::{{closure}}::h10dfc05fbca7f3e2
    43:     0x7ff6546b06dc - bindgen::<impl bindgen::options::BindgenOptions>::process_comment::{{closure}}::hf96a8c739f753b77
    44:     0x7ff6546adebf - bindgen::Builder::generate::hfa833464a875736d
    45:     0x7ff6545e43b4 - std::rt::lang_start::h59a2f7e494df77dd
    46:     0x7ff6545e19e6 - std::rt::lang_start::h59a2f7e494df77dd
    47:     0x7ff6545e1009 - __ImageBase
    48:     0x7ff6545e169c - std::rt::lang_start::h59a2f7e494df77dd
    49:     0x7ff654b36418 - std::rt::lang_start_internal::closure$2
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\rt.rs:148
    50:     0x7ff654b36418 - std::panicking::try::do_call
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\panicking.rs:502
    51:     0x7ff654b36418 - std::panicking::try
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\panicking.rs:466
    52:     0x7ff654b36418 - std::panic::catch_unwind
ary\std\src\rt.rs:148
    54:     0x7ff6545e1677 - std::rt::lang_start::h59a2f7e494df77dd
    55:     0x7ff6545e4829 - main
    56:     0x7ff654b6ade0 - invoke_main
                                 at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    57:     0x7ff654b6ade0 - __scrt_common_main_seh
                                 at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    58:     0x7ffcbdec26ad - BaseThreadInitThunk
    59:     0x7ffcbe5ea9f8 - RtlUserThreadStart
```

My `cargo.toml`:
```
[package]
name = "dftest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enet-sys = "1.0.4"
```

I'm using the MSVC toolchain. Thanks

**Comment by ruabmbua** [comment]
I can not reproduce your problem in my windows 10 VM with latest rust stable.
What version of windows are you using?

Also, are you using the latest version of rust-bindgen? Have you run cargo update?

Maybe its related to this issue: https://github.com/rust-lang/rust-bindgen/issues/2500

**Comment by ghost** [comment]
I'm using Windows 11. I'll try to reinstall Rust and MSVC though

**Comment by ghost** [comment]
Okay, I had some other clang in my PATH and removed it. That helped.
